---
- name: Fetch scrape log
  ansible.builtin.fetch:
    src: "{{ work_dir }}/{{ log_destination }}"
    dest: "{{export_dir}}/{{ ansible_host }}-scrape.log"
    validate_checksum: false # it keeps changing as resources are scraped
    flat: true

- name: "Retrieve getsetfetch.service status"
  ansible.builtin.shell: systemctl status getsetfetch.service
  register: systemctl

- name: "Copy getsetfetch.service status output to local file"
  delegate_to: localhost
  ansible.builtin.copy:
    dest: "{{export_dir}}/{{ inventory_hostname }}-systemd-status.log"
    # content: "{{ systemctl.stdout }}\n\n{{ journalctl.stdout }}"
    content: "{{ systemctl.stdout }}"

- name: Fetch getsetfetch.service output and error logs
  ansible.builtin.fetch:
    src: "{{ work_dir }}/{{item}}.log"
    dest: "{{export_dir}}/{{ ansible_host }}-systemd-{{item}}.log"
    validate_checksum: false # it keeps changing as resources are scraped
    flat: true
  with_items:
    - output
    - error