- hosts: all
  vars_files:
    - vault.yml

  roles:
    - role: gsf-scraper-setup
      vars:
        db:
          name: getsetfetch
          user: "{{ vault_db_user }}"
          password: "{{ vault_db_password }}"
          pool:
            min: 10
            max: 10
        scraper:
          uv_threadpool_size: 34 # 4 (default) + 30 (max concurrent dns.lookups)
          npm_install:
            - knex@1.0.7
            - pg@8.7.3
            - cheerio@1.0.0-rc.10
            - "@get-set-fetch/scraper@0.11.0"
            # - get-set-fetch-scraper-0.10.0.tgz
          log:
            level: info
          files:
              scrape_urls: majestic-million-compact.csv
              gsf_config: templates/js-scripts-config.json.j2
              additional:
                  - ExtractScriptsPlugin.js