version: "3.3"
services:
  pg:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: gsf-user
      POSTGRES_PASSWORD: gsf-pswd
      POSTGRES_DB: gsf-db
    ports:
      - 54320:5432

  gsf:
    image: getsetfetch:latest
    working_dir: /home/pptruser/scraper
    volumes:
      - ./data:/home/pptruser/scraper/data
    command: sh -c "./bin/gsfscrape --config ./data/config.json --loglevel debug --logdestination ./data/scrape.log --save --overwrite --scrape --export ./data/project.csv"
    security_opt:
      - seccomp:"./chrome.json"
    depends_on:
    - pg
      
volumes:
  data: