version: "3.3"
services:
  pg:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: gsf-user
      POSTGRES_PASSWORD: gsf-pswd
      POSTGRES_DB: gsf-db

  gsf:
    image: getsetfetch:latest
    command: >
      --version
      --config data/config-pg-puppeteer.json
      --save
      --overwrite
      --scrape
      --loglevel info
      --logdestination data/scrape.log
      --export data/export.csv

    volumes:
      - ../data:/home/gsfuser/scraper/data
    security_opt:
      - seccomp:"../data/chromium-security-profile.json"
    depends_on:
    - pg
      
volumes:
  data: