---
- name: "Retrieve systemd log messages since last boot"
  ansible.builtin.shell: "journalctl -u postgresql -b"
  register: journalctl

- name: "Retrieve service status"
  ansible.builtin.shell: systemctl status postgresql
  register: systemctl

- name: "Copy output to local file"
  delegate_to: localhost
  ansible.builtin.copy:
    dest: "{{export_dir}}/pg-{{ inventory_hostname }}-systemd.log"
    content: "{{ systemctl.stdout }}\n\n{{ journalctl.stdout }}"

- name: "Copy output to local file"
  ansible.builtin.fetch:
    src: "/var/log/postgresql/postgresql-14-main.log"
    dest: "{{export_dir}}/pg-{{ ansible_host }}-main.log"
    validate_checksum: false # it keeps changing as resources are scraped
    flat: true
