name: audit

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main, next ]

jobs:
  audit:
    if: ${{ !github.event.act }}
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 15
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: NPM Audit
      run: npm audit --audit-level=high