name: audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: NPM Audit
      run: npm audit --audit-level=high