name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_test:
    name: Non-storage unit tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Install required peer dependencies
      run: npm install knex --save
    - name: Install Puppeteer without browser
      run: export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true && npm install puppeteer --save

    - name: Unit tests
      run: npm run test:unit

  sqlite_test:
    name: Sqlite3 tests
    runs-on: ubuntu-18.04
    needs: unit_test

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Install Sqlite3 peer dependencies
      run: npm install knex sqlite3 --save
    - name: Install Puppeteer
      run: npm install puppeteer --save

    - name: Sqlite3 unit tests
      run: npm run test:storage:sqlite:unit

    - name: Sqlite3 integration tests
      run: npm run test:storage:sqlite:integration

  mysql_test:
    name: MySQL tests
    runs-on: ubuntu-18.04
    needs: unit_test

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: MySQL up
      run: docker-compose -f ./test/storage/mysql/mysql.yml up -d

    - name: Install dependencies
      run: npm ci
    - name: Install MySQL peer dependencies
      run: npm install knex mysql --save
    - name: Install Puppeteer
      run: npm install puppeteer --save

    - name: MySQL unit tests
      run: npm run test:storage:mysql:unit

    - name: MySQL integration tests
      run: npm run test:storage:mysql:integration

    - name: MySQL down
      run: docker-compose -f ./test/storage/mysql/mysql.yml down

  pg_test:
    name: PostgreSQL tests
    runs-on: ubuntu-18.04
    needs: unit_test

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Install PostgreSQL peer dependencies
      run: npm install knex pg --save
    - name: Install Puppeteer
      run: npm install puppeteer --save

    - name: PostgreSQL up
      run: docker-compose -f ./test/storage/pg/pg.yml up -d

    - name: PostgreSQL unit tests
      run: npm run test:storage:pg:unit

    - name: PostgreSQL integration tests
      run: npm run test:storage:pg:integration

    - name: PostgreSQL down
      run: docker-compose -f ./test/storage/pg/pg.yml down