name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  non_storage:
    name: Non-Storage
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci

    - name: Non-storage unit tests
      run: npm run test:unit:non-storage

  puppeteer_chromium:
    name: Puppeteer - Chromium - ${{ matrix.storage }}
    runs-on: ubuntu-18.04
    needs: non_storage

    strategy:
      fail-fast: false
      matrix:
        storage: [Sqlite3, MySQL, PostgreSQL]
        include:
          - storage: Sqlite3
            npm_deps: knex sqlite3
            test: sqlite
            docker_file: 
          - storage: MySQL
            npm_deps: knex mysql
            test: mysql
            docker_file: ./test/config/storage/mysql/mysql.yml 
          - storage: PostgreSQL
            npm_deps: knex pg
            test: pg
            docker_file: ./test/config/storage/pg/pg.yml 

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: ${{ matrix.storage }} up
      run: /bin/sh -c 'docker_file="${{ matrix.docker_file }}"; if [ $docker_file ]; then docker-compose -f ${{ matrix.docker_file }} up -d; else echo "ignored, no docker file"; fi'
      
    - name: Install dependencies
      run: npm ci
    - name: Install ${{ matrix.storage }} peer dependencies
      run: npm install ${{ matrix.npm_deps }} --save
    - name: Install Puppeteer
      run: npm install puppeteer --save

    - name: ${{ matrix.storage }} unit tests
      run: npx mocha --config test/.mocharc.js \"test/unit/storage/${{ matrix.test }}-unit-suite.ts\"

    - name: ${{ matrix.storage }} - Puppeteer - Chromium acceptance tests
      run: npx mocha --config test/.mocharc.js \"test/acceptance/${{ matrix.test }}-puppeteer-chromium.ts\"

    - name: ${{ matrix.storage }} down
      run: /bin/sh -c 'docker_file="${{ matrix.docker_file }}"; if [ $docker_file ]; then docker-compose -f ${{ matrix.docker_file }} down; else echo "ignored, no docker file"; fi'
     

  playwright_chromium:
    name: Sqlite3 - Playwright - Chromium
    runs-on: ubuntu-18.04
    needs: non_storage

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Install Sqlite3 peer dependencies
      run: npm install knex sqlite3 --save
    - name: Install Playwright
      run: npm install playwright-core playwright-chromium --save

    - name: Sqlite3 - Puppeteer - Chromium acceptance tests
      run: npm run test:acceptance:sqlite-playwright-chromium