name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  non_storage:
    name: Non-storage
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Install required peer dependencies
      run: export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true && npm install knex puppeteer --save

    - name: Non-storage unit tests
      run: npm run test:unit:non-storage

  sqlite_puppeteer_chromium:
    name: Sqlite3 - Puppeteer - Chromium
    runs-on: ubuntu-18.04
    needs: non_storage

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Install Sqlite3 peer dependencies
      run: npm install knex sqlite3 --save
    - name: Install Puppeteer
      run: npm install puppeteer --save

    - name: Sqlite3 unit tests
      run: npm run test:unit:sqlite

    - name: Sqlite3 - Puppeteer - Chromium acceptance tests
      run: npm run test:acceptance:sqlite-puppeteer-chromium

  mysql_puppeteer_chromium:
    name: MySQL tests
    runs-on: ubuntu-18.04
    needs: non_storage

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: MySQL up
      run: docker-compose -f ./test/storage/mysql/mysql.yml up -d

    - name: Install dependencies
      run: npm ci
    - name: Install MySQL peer dependencies
      run: npm install knex mysql --save
    - name: Install Puppeteer
      run: npm install puppeteer --save

    - name: MySQL unit tests
      run: npm run test:unit:mysql

    - name: MySQL - Puppeteer - Chromium acceptance tests
      run: npm run test:acceptance:mysql-puppeteer-chromium

    - name: MySQL down
      run: docker-compose -f ./test/storage/mysql/mysql.yml down

  pg_puppeteer_chromium:
    name: PostgreSQL tests
    runs-on: ubuntu-18.04
    needs: non_storage

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Install PostgreSQL peer dependencies
      run: npm install knex pg --save
    - name: Install Puppeteer
      run: npm install puppeteer --save

    - name: PostgreSQL up
      run: docker-compose -f ./test/storage/pg/pg.yml up -d

   - name: PostgreSQL unit tests
      run: npm run test:unit:pg

    - name: PostgreSQL - Puppeteer - Chromium acceptance tests
      run: npm run test:acceptance:pg-puppeteer-chromium

    - name: PostgreSQL down
      run: docker-compose -f ./test/storage/pg/pg.yml down